### ISSUE TITLE
cobgen causing client crashes on server

### ISSUE THREAD

**Issue by MoonMoonShark** [LexManos/CobbleForDays#15]
i have a recurring problem that people coming to my base on my server crash within seconds arriving. there is nothing in the error log that is useful or helpful, but as soon as i remove the cobgen, they stop crashing and can now walk around just fine. i have only recently built my base, in a small cave, so i don't have much in there. i took out every item, one at a time, and narrowed it down to the cobgen. i tried with every level of generator, both made by me and taken out of creative inventory, and no matter what i did, when there was a cobgen, the client crashed, and when it wasn't, they didn't. i even went into the server world files, deleted the region altogether and rebuilt it, and with a completely fresh area, nothing at all built there, if they were standing next to me, and i put down a cobgen, they immediately crashed out of the game.

i moved to a completely different area of the world, and am now having the same issue. next time it happens, i will try to have them send me the crash file, latest.log, and debug. the infuriating part is that it doesn't crash for ME, and i have no idea why THEY crash but _I_ don't.

modpack: https://www.curseforge.com/minecraft/modpacks/the-lighthouse

Minecraft: 1.16.5
Forge: 36.1.16
CobbleForDays: 1.3.1

**Comment by LexManos** [comment]
Issues will not be considered with vague "I think something crashes and it's your fault" descriptions. To my knowledge there is nothing in this mod that CAN reasonably crash. So until this includes a log at the very least, not gunna care.

**Comment by MoonMoonShark** [comment]
yessir.

**Comment by MoonMoonShark** [comment]
fyi i finally managed to get a log this morning from a client on the server who got stuck in a crash loop, trying to go home. looks like voxelmap is throwing a hissyfit over the cobgen being a ticking entity. i'll report this to voxelmap. i appreciate your patience and time on this matter.

**Comment by MoonMoonShark** [comment]
please reopen this ticket, as the issue is still ongoing, and it IS a cobgen issue.

`[21:20:05] [Render thread/WARN]: Block entity invalid: cobblefordays:tier_3 @ MutableBlockPos{x=-268, y=0, z=1205}
[21:20:08] [Render thread/FATAL]: Preparing crash report with UUID 1f89a714-3a48-45a8-92ea-e09987536d13
[21:20:08] [Render thread/FATAL]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_51]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_51]
	at net.minecraft.world.World.func_217391_K(World.java:481) ~[?:?]
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1510967269.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[21:20:24] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]`


we have determined that it IS a cobgen issue, involving all 5 levels of the cobgen. 

[latest (11).log](https://github.com/LexManos/CobbleForDays/files/6667449/latest.11.log)

at this point, if a player crashes on my server, it has been determined to be a cobgen issue, and the only way they can sign back on to the server, without me going into their player profile on the server and moving them somewhere else, is if we remove the cobgen from the area where they crashed.
