### ISSUE TITLE
cobgen on server causing client crashes

### ISSUE THREAD

**Issue by MoonMoonShark** [LexManos/CobbleForDays#16]
i have a recurring problem that users on my server crash within seconds of arriving at any location with a cobgen. as soon as i remove the cobgen, they stop crashing and can now walk around just fine. 

at one location, in order to determine if there was an object at the location causing the problem, i removed every item, one at a time, then had someone come to that location. they continued to crash, every single time, until i removed the cobgen. once i had removed it, they could walk around freely with no problems. i tried all 5 levels, both manually created in survival mode and pulled directly out of creative. in every instance, the other player's client crashed immediately upon placing the cobgen in the world. if there was no cobgen, they could walk around fine. i went so far as to delete the region file altogether, to ensure that it was a completely blank slate, and as soon as the cobgen was placed, their client crashed.

modpack: https://www.curseforge.com/minecraft/modpacks/the-lighthouse

Minecraft: 1.16.5
Forge: 36.1.16
CobbleForDays: 1.3.1

while there is never anything listed in the debug file, i've found that consistently, if someone's client crashes while they're on my server, it's usually because there is a cobgen present at the place where they were kicked off, and the only way to get them back into the server is to either teleport them to a different place in the world before they log on, or remove the cobgen. i don't know WHY it's a problem, but i know that it IS a problem, and it has been determined to be a cobgen problem, involving all 5 tiers.

i would be happy to whitelist you on my server for the purposes of diagnosing and testing this issue.

[latest (11).log](https://github.com/LexManos/CobbleForDays/files/6667691/latest.11.log)

`[21:20:05] [Render thread/WARN]: Block entity invalid: cobblefordays:tier_3 @ MutableBlockPos{x=-268, y=0, z=1205}
[21:20:08] [Render thread/FATAL]: Preparing crash report with UUID 1f89a714-3a48-45a8-92ea-e09987536d13
[21:20:08] [Render thread/FATAL]: Unreported exception thrown!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_51]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_51]
	at net.minecraft.world.World.func_217391_K(World.java:481) ~[?:?]
	at net.minecraft.client.world.ClientWorld.func_217419_d(ClientWorld.java:175) ~[?:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1483) ~[?:?]
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:953) ~[?:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?]
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.16.jar:36.1]
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$477/1510967269.call(Unknown Source) [forge-1.16.5-36.1.16.jar:36.1]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?]
[21:20:24] [Render thread/INFO]: [net.minecraft.util.registry.Bootstrap:func_179870_a:123]`

**Comment by LexManos** [comment]
Don't spam my github. The last one was denied, as is this one. Concurrents have never showen up in any of my tests or anyone else's uses.
Just because my mod happens to be one line above your crash {happened 3 seconds before  it} doesn't mean it's my problem.
